/**
 * Building curl invocations without ever handing user data to a shell.
 *
 * Neutralino's `os.execCommand` runs its argument through the platform shell
 * (`/bin/sh -c` on Unix, `cmd.exe /c` on Windows). Interpolating a password or
 * a URL into that string is remote code execution waiting to happen, and no
 * amount of ad-hoc quoting fixes it portably — POSIX and cmd.exe disagree about
 * almost everything, and cmd.exe expands `%VAR%` inside double quotes.
 *
 * So the shell never sees user data at all. The command is the constant
 * `curl -q --config -`, and the entire request — URL, headers, body, token —
 * travels over stdin as a curl config file. Escaping then reduces to curl's own
 * small, documented grammar rather than two shells' worth of metacharacters.
 *
 * `-q` must stay first: it stops curl reading `~/.curlrc` (or `%APPDATA%\_curlrc`),
 * which could otherwise inject `--insecure` or a proxy behind our back.
 *
 * @see https://curl.se/docs/manpage.html#-K
 */

import { AppError, ErrorCode } from './errors.js';

/** The complete, constant command line. Nothing is ever appended to this. */
export const CURL_COMMAND = 'curl -q --config -';

/** Minimum curl release that understands `--connect-to`, which the pinning path needs. */
export const MIN_CURL_VERSION = [7, 49, 0];

/**
 * Minimum curl release on Windows, where `--ssl-revoke-best-effort` is also
 * required. See `tolerateUnknownRevocation` below.
 */
export const MIN_CURL_VERSION_SCHANNEL = [7, 70, 0];

const DEFAULT_CONNECT_TIMEOUT_SECONDS = 15;
const DEFAULT_MAX_TIME_SECONDS = 45;

/**
 * Escape a string for use as a double-quoted value in a curl config file.
 *
 * curl recognises exactly these escapes inside a quoted parameter: `\\`, `\"`,
 * `\t`, `\n`, `\r`, `\v`. Anything else has no representation, so a value
 * carrying another control character is rejected rather than silently mangled.
 *
 * @param {string} value
 * @returns {string} the value including its surrounding double quotes
 */
export function quoteConfigValue(value) {
  if (typeof value !== 'string') {
    throw new AppError(ErrorCode.INVALID_INPUT, 'Internal error: request field was not text.');
  }

  let out = '"';
  for (const char of value) {
    const code = char.codePointAt(0);

    if (char === '\\') { out += '\\\\'; continue; }
    if (char === '"') { out += '\\"'; continue; }
    if (char === '\t') { out += '\\t'; continue; }
    if (char === '\n') { out += '\\n'; continue; }
    if (char === '\r') { out += '\\r'; continue; }
    if (char === '\v') { out += '\\v'; continue; }

    if (code < 0x20 || code === 0x7f) {
      throw new AppError(
        ErrorCode.INVALID_INPUT,
        'That value contains a control character that cannot be sent safely. Remove it and try again.',
        { detail: `rejected control character U+${code.toString(16).padStart(4, '0').toUpperCase()}` },
      );
    }

    out += char;
  }
  return out + '"';
}

/**
 * @typedef {object} CurlRequest
 * @property {string}   url          absolute https:// URL
 * @property {'GET'|'POST'} [method]
 * @property {Record<string,string>} [headers]
 * @property {string}   [body]       raw request body, sent verbatim
 * @property {Array<[string,string]>} [query] params curl will URL-encode and append
 * @property {string}   [caCertPath] verify the peer against this CA bundle instead of the system store
 * @property {{host: string, port: number, toHost: string, toPort: number}} [connectTo]
 *           dial `toHost:toPort` but complete the TLS handshake, and validate the
 *           certificate, as `host:port`
 * @property {number}   [connectTimeoutSeconds]
 * @property {number}   [maxTimeSeconds]
 * @property {boolean}  [tolerateUnknownRevocation]
 *           Accept a certificate whose revocation status cannot be determined
 *           because no distribution point exists. Needed on Windows only — see
 *           the note in `buildCurlConfig`.
 */

/**
 * Render a request as a curl config-file document.
 *
 * @param {CurlRequest} request
 * @returns {string} the document to write to curl's stdin
 */
export function buildCurlConfig(request) {
  if (!request || typeof request.url !== 'string' || !request.url) {
    throw new AppError(ErrorCode.INVALID_INPUT, 'Internal error: a request was built without a URL.');
  }
  if (!request.url.startsWith('https://')) {
    throw new AppError(
      ErrorCode.PROTOCOL,
      'Refusing to send credentials over an unencrypted connection.',
      { detail: `non-https URL: ${request.url.slice(0, 60)}` },
    );
  }

  const lines = [
    '# generated by PIA WireGuard Generator - do not edit',
    `url = ${quoteConfigValue(request.url)}`,
    // Never let a redirect or a crafted URL downgrade the transport.
    'proto = "=https"',
    'proto-redir = "=https"',
    'tlsv1.2',
    'silent',
    'show-error',
    // No `location`: we do not follow redirects while carrying credentials.
    `connect-timeout = ${toPositiveInteger(request.connectTimeoutSeconds, DEFAULT_CONNECT_TIMEOUT_SECONDS)}`,
    `max-time = ${toPositiveInteger(request.maxTimeSeconds, DEFAULT_MAX_TIME_SECONDS)}`,
    // Appended after the body so the HTTP status survives even when curl exits 0
    // on a 500. Parsed back out by `parseCurlOutput`.
    'write-out = "\\n%{http_code}"',
  ];

  if (request.method === 'POST') {
    lines.push('request = "POST"');
  }

  for (const [name, value] of Object.entries(request.headers || {})) {
    lines.push(`header = ${quoteConfigValue(`${name}: ${value}`)}`);
  }

  if (typeof request.body === 'string') {
    // `data-raw`, not `data`: `data` treats a leading `@` as a filename to read.
    lines.push(`data-raw = ${quoteConfigValue(request.body)}`);
  }

  if (request.query && request.query.length > 0) {
    lines.push('get');
    for (const [name, value] of request.query) {
      assertQueryParamName(name);
      lines.push(`data-urlencode = ${quoteConfigValue(`${name}=${value}`)}`);
    }
  }

  if (request.caCertPath) {
    lines.push(`cacert = ${quoteConfigValue(request.caCertPath)}`);
  }

  if (request.tolerateUnknownRevocation) {
    // Windows curl uses Schannel, which checks revocation and treats "cannot
    // determine" as failure. Private Internet Access's root publishes neither a
    // CRL nor an OCSP responder — quite normal for a private CA — so every
    // pinned request on Windows would otherwise die with
    // `CERT_TRUST_REVOCATION_STATUS_UNKNOWN` and curl exit 60.
    //
    // `--ssl-revoke-best-effort` relaxes exactly that case: revocation data
    // being *absent or unreachable* is tolerated, while a certificate that is
    // actually revoked is still rejected, and the chain is still verified
    // against the pinned CA. It is not `--ssl-no-revoke`, and it is emphatically
    // not `--insecure`.
    lines.push('ssl-revoke-best-effort');
  }

  if (request.connectTo) {
    const { host, port, toHost, toPort } = request.connectTo;
    lines.push(`connect-to = ${quoteConfigValue(`${host}:${port}:${toHost}:${toPort}`)}`);
  }

  return lines.join('\n') + '\n';
}

/**
 * Split the trailing `--write-out` status marker off a curl response.
 *
 * curl always appends "\n<3-digit status>" last, so the final line is the
 * status no matter what the body contained.
 *
 * @param {string} stdOut
 * @returns {{body: string, status: number}} status is 0 when curl wrote nothing
 */
export function parseCurlOutput(stdOut) {
  if (typeof stdOut !== 'string' || stdOut === '') {
    return { body: '', status: 0 };
  }

  const cut = stdOut.lastIndexOf('\n');
  if (cut === -1) {
    // No marker at all: curl died before writing anything useful.
    return { body: stdOut, status: 0 };
  }

  const trailer = stdOut.slice(cut + 1).trim();
  if (!/^\d{3}$/.test(trailer)) {
    return { body: stdOut, status: 0 };
  }

  return { body: stdOut.slice(0, cut), status: Number(trailer) };
}

/**
 * Parse the version out of `curl --version` output.
 *
 * @param {string} versionOutput
 * @returns {[number, number, number] | null}
 */
export function parseCurlVersion(versionOutput) {
  const match = /^curl\s+(\d+)\.(\d+)(?:\.(\d+))?/m.exec(versionOutput || '');
  if (!match) return null;
  return [Number(match[1]), Number(match[2]), Number(match[3] || 0)];
}

/**
 * @param {[number,number,number]} actual
 * @param {[number,number,number]} minimum
 * @returns {boolean}
 */
export function isVersionAtLeast(actual, minimum) {
  for (let i = 0; i < 3; i++) {
    if (actual[i] > minimum[i]) return true;
    if (actual[i] < minimum[i]) return false;
  }
  return true;
}

function toPositiveInteger(value, fallback) {
  return Number.isInteger(value) && value > 0 ? value : fallback;
}

function assertQueryParamName(name) {
  if (!/^[A-Za-z0-9_.-]+$/.test(name)) {
    throw new AppError(ErrorCode.INVALID_INPUT, 'Internal error: invalid query parameter name.');
  }
}
